version: "3.9"
services:
  redis:
    image: redis
    expose:
      - "6379"
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - ./.data/postgres/pgdata:/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      CONTACT: ${CONTACT}
      VENMO: ${VENMO}
      DEBUG: ${DEBUG}
      SEND: ${DEBUG}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DATABASE: ${DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: "db"
      PG_PORT: ${PG_PORT}
      REDIS_SERVER: "redis"
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_KEY: ${TWILIO_KEY}
      TWILIO_NUM: ${TWILIO_NUM}
