[tool.ruff]
line-length = 99
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    "venv",
    ".venv",
]
