version: 2.1

jobs:
  build:
    working_directory: ~/fbsurvivor2
    docker:
      - image: circleci/python:3.8
          environment: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv install
  test:
    steps:
      - run: pytest .
  deploy:
    steps:
      - run: echo "Complete"

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
