version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.8.3'
      - image: 'circleci/postgres:12'
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv run pytest .
      - run: echo 'hello world'
