version: 2.0
jobs:
  build:
    working_directory: ~/fbsurvivor2
    docker:
      - image: circleci/python:3.8.3
        environment:
          - DOMAIN=127.0.0.1:8000
          - DATABASE=fbsurvivor2
          - PG_USER=root
          - PG_PASSWORD=pgpassword
          - SECRET_KEY=some_secret_key_eh
      - image: circleci/postgres:12
        environment:
          - POSTGRES_PASSWORD=pgpassword
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --python 3.8
      - run:
          command: |
            black --check .
      - run:
          command: |
            pipenv run pytest . |
