version: 2.1

jobs:
  build:
    working_directory: ~/fbsurvivor2
    docker:
      - image: circleci/python:3.8
          environment:
            DATABASE: circle_test
            PG_HOST: 127.0.0.1
            PG_USER: root
      - image: circleci/postgres:9.6.2
          environment:
            POSTGRES_DB: circle_test_test
            POSTGRES_USER: root
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv install
  test:
    steps:
      - run: pytest .
  deploy:
    steps:
      - run: echo "Complete"

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
