# Generated by Django 3.0.5 on 2020-04-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("link", models.CharField(max_length=44, unique=True)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_email_confirmed", models.BooleanField(default=False)),
                ("is_phone_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("is_locked", models.BooleanField(default=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_num", models.PositiveSmallIntegerField()),
                ("lock_datetime", models.DateTimeField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_code", models.CharField(max_length=3)),
                ("bye_week", models.PositiveSmallIntegerField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_retired", models.BooleanField(default=False)),
                ("is_survivor", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Player"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("W", "WIN"), ("L", "LOSS"), ("R", "RETIRED")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.Team",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Week"
                    ),
                ),
            ],
        ),
    ]
