# Generated by Django 3.0.5 on 2020-04-02 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerstatus",
            options={"verbose_name_plural": "playerstatuses"},
        ),
        migrations.AddField(
            model_name="player",
            name="confirmation_code",
            field=models.IntegerField(
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(111111),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
