# Generated by Django 3.0.5 on 2020-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20200409_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pick",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[("W", "WIN"), ("L", "LOSS"), ("R", "RETIRED")],
                max_length=1,
                null=True,
            ),
        ),
    ]
