# Generated by Django 3.1a1 on 2020-05-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("core", "0006_auto_20200517_1258"),
        ("core", "0007_auto_20200517_1359"),
        ("core", "0008_auto_20200517_1403"),
    ]

    dependencies = [
        ("core", "0005_auto_20200409_1957"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_email_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="has_phone_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pick",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.team",
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="lock_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="pick",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.team",
            ),
        ),
        migrations.AlterField(
            model_name="pick",
            name="result",
            field=models.CharField(
                choices=[("W", "WIN"), ("L", "LOSS"), ("R", "RETIRED")],
                max_length=1,
                null=True,
            ),
        ),
    ]
