# Generated by Django 3.0.6 on 2020-05-30 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20200524_1839"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="confirmation_code",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_email_confirmed",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_phone_confirmed",
        ),
    ]
