# Generated by Django 3.0.6 on 2020-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
