# Generated by Django 3.0.6 on 2020-05-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20200530_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="has_email_reminders",
            field=models.BooleanField(default=True),
        ),
    ]
