# Generated by Django 3.2.4 on 2021-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_auto_20210408_1919"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignUpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
            ],
        ),
    ]
