# Generated by Django 3.2.4 on 2021-08-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_signupcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="link",
            field=models.CharField(
                default="",
                max_length=44,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Lock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lock_datetime", models.DateTimeField(null=True)),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.team"),
                ),
                (
                    "week",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.week"),
                ),
            ],
        ),
    ]
