# Generated by Django 3.2.4 on 2021-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_auto_20210821_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="league",
            field=models.CharField(default="original", max_length=12),
        ),
    ]
