# Generated by Django 3.2.4 on 2021-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20210825_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
