# Generated by Django 3.2.4 on 2021-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_player_is_dark_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="emoji",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
