# Generated by Django 4.1.3 on 2022-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_player_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="", max_length=15),
        ),
    ]
