# Generated by Django 4.1.3 on 2022-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="old_links",
            field=models.TextField(blank=True, default=""),
        ),
    ]
