# Generated by Django 4.1.7 on 2023-03-17 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_player_old_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="has_phone_reminders",
        ),
        migrations.RemoveField(
            model_name="player",
            name="phone",
        ),
    ]
