# Generated by Django 4.2 on 2023-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_player_has_phone_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_advanced_security",
            field=models.BooleanField(default=False),
        ),
    ]
