# Generated by Django 4.2 on 2023-06-18 20:11

from django.db import migrations, models
import fbsurvivor.core.models.player


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_player_has_advanced_security"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="player",
            name="core_player_link_38fca8_idx",
        ),
        migrations.RemoveField(
            model_name="player",
            name="has_advanced_security",
        ),
        migrations.RemoveField(
            model_name="player",
            name="link",
        ),
        migrations.RemoveField(
            model_name="player",
            name="old_links",
        ),
        migrations.AddField(
            model_name="player",
            name="secret",
            field=models.CharField(
                default=fbsurvivor.core.models.player.generate_secret, max_length=32
            ),
        ),
    ]
