# Generated by Django 4.2 on 2023-06-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_remove_player_core_player_link_38fca8_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="secret",
        ),
        migrations.CreateModel(
            name="TokenHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hash", models.CharField(max_length=128)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        related_query_name="token",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tokenhash",
            index=models.Index(fields=["hash"], name="core_tokenh_hash_f5b5bb_idx"),
        ),
    ]
