# Generated by Django 4.2 on 2023-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_remove_player_secret_tokenhash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_push_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="ntfy_topic",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="emoji",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="player",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
