# Generated by Django 4.2 on 2023-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_player_has_push_reminders_player_ntfy_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="ntfy_topic",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
    ]
