# Generated by Django 4.2 on 2023-07-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_player_ntfy_topic"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["username"], name="core_player_usernam_e4d538_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["email"], name="core_player_email_a55971_idx"),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["year"], name="core_season_year_483c37_idx"),
        ),
    ]
