# Generated by Django 4.2 on 2023-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_player_core_player_usernam_e4d538_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="has_push_reminders",
        ),
        migrations.RemoveField(
            model_name="player",
            name="ntfy_topic",
        ),
        migrations.AddField(
            model_name="player",
            name="has_sms_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
