# Generated by Django 4.2.5 on 2023-10-15 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_remove_player_has_push_reminders_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="has_sms_reminders",
        ),
        migrations.RemoveField(
            model_name="player",
            name="phone_number",
        ),
    ]
