name: CI

on:
  push:
    paths:
      - "fbsurvivor/**"
      - "requirements/**"

jobs:
  check:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      ENV: dev
      DOMAIN: http://127.0.0.1:8000
      SECRET_KEY: abcdefghijklmnop
      PGDATABASE: ci
      PGUSER: postgres
      PGPASSWORD: password
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt --no-deps
      - name: Run Ruff
        run: ruff check .
      - name: Run Black
        run: black --check .
      - name: Run Tests
        run: pytest -p no:warnings .
